"""One-shot script to produce every number the paper's Results section needs.

Why this exists
---------------
The four analysis notebooks (dataset_characterization, rq1_structural_nature,
rq2_resolution_strategies, rq3_resolver) each print or plot the same core
aggregates we ultimately want in the paper. This script calls the shared
helpers in ``analysis.common`` once, rolls up everything to plain dict/JSON,
and writes two files in ``analysis/results/``:

* ``results_summary.json`` -- machine-readable, full precision;
* ``results_summary.txt``  -- flat, human-readable dump for quick inspection.

How to run
----------
From the project root, with the Python environment that has pandas / pyarrow::

    python -m analysis.run_all_analyses

or::

    python analysis/run_all_analyses.py

The script does NOT execute the notebooks (no matplotlib / no figures). Its
only job is to produce the numbers. Figures are still generated by the
notebooks themselves.

What it reports
---------------
1.  Dataset characterisation (raw AIDev universe + our conflict subset).
2.  RQ1 -- structural profile: chunks-per-merge distribution, LOC stats,
    conflict incidence per stratum.
3.  RQ2 -- resolution strategies: distribution with and without the
    Imprecise bucket, plus the Imprecise share per stratum.
4.  RQ3 -- resolver split (agent vs human) and strategy differences.

The script is deliberately defensive: every section is wrapped so a missing
table does not break the others.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import pandas as pd

# Make ``python analysis/run_all_analyses.py`` work as well as ``-m`` form.
_HERE = Path(__file__).resolve().parent
_ROOT = _HERE.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from analysis.common import (  # noqa: E402
    DATA_DIR,
    STRATEGY_ORDER,
    AnalysisTables,
    build_chunk_frame,
    build_merge_frame,
    build_pr_frame,
    descriptive_table,
    imprecise_share,
    load_tables,
    pr_fanout,
    strategy_distribution,
)


RESULTS_DIR = _ROOT / "analysis" / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #


def _safe_len(df: pd.DataFrame) -> int:
    return int(len(df)) if df is not None else 0


def _series_to_dict(s: pd.Series) -> dict[str, Any]:
    return {str(k): (float(v) if pd.notna(v) else None) for k, v in s.items()}


def _df_to_records(df: pd.DataFrame) -> list[dict[str, Any]]:
    if df is None or df.empty:
        return []
    out = df.reset_index().to_dict(orient="records")
    # JSON-safe: convert numpy scalars, NaN -> None.
    cleaned = []
    for row in out:
        cleaned.append({
            k: (None if (isinstance(v, float) and pd.isna(v)) else
                (float(v) if hasattr(v, "item") and isinstance(v, (pd.Int64Dtype, pd.Float64Dtype))
                 else v.item() if hasattr(v, "item") else v))
            for k, v in row.items()
        })
    return cleaned


def _pct(num: float, denom: float) -> float:
    if denom <= 0:
        return 0.0
    return 100.0 * num / denom


# --------------------------------------------------------------------------- #
# Dataset characterisation
# --------------------------------------------------------------------------- #


def _raw_aidev_universe_stats() -> dict[str, Any]:
    """Counts from the raw AIDev parquets (if present alongside ``data/raw/``)."""
    # Look for the AIDev raw drop in the two most common locations.
    candidates = [
        _ROOT / "data" / "raw" / "aidev" / "all_pull_request.parquet",
        _ROOT / "data" / "aidev" / "all_pull_request.parquet",
        _ROOT / "data" / "all_pull_request.parquet",
    ]
    pr_path = next((p for p in candidates if p.exists()), None)
    if pr_path is None:
        return {"note": "raw AIDev parquet not found; skipping raw-universe stats"}

    repo_path_candidates = [
        pr_path.parent / "all_repository.parquet",
        _ROOT / "data" / "raw" / "aidev" / "all_repository.parquet",
    ]
    repo_path = next((p for p in repo_path_candidates if p.exists()), None)

    out: dict[str, Any] = {"pr_parquet": str(pr_path)}
    try:
        prs = pd.read_parquet(pr_path, columns=[c for c in (
            "id", "repo_full_name", "full_name", "agent", "language", "state",
        ) if True])
    except Exception as exc:  # schema varies across AIDev drops
        prs = pd.read_parquet(pr_path)
        out["pr_read_note"] = f"full read (column selection failed: {exc})"

    out["aidev_total_prs"] = int(len(prs))
    repo_col = "repo_full_name" if "repo_full_name" in prs.columns else (
        "full_name" if "full_name" in prs.columns else None
    )
    if repo_col:
        out["aidev_total_repos"] = int(prs[repo_col].nunique())
    if "agent" in prs.columns:
        out["aidev_prs_per_agent"] = prs["agent"].value_counts().to_dict()
    if "language" in prs.columns:
        out["aidev_prs_per_language_top15"] = (
            prs["language"].fillna("Unknown").value_counts().head(15).to_dict()
        )
    if "state" in prs.columns:
        out["aidev_prs_per_state"] = prs["state"].value_counts().to_dict()

    if repo_path is not None:
        try:
            repos = pd.read_parquet(repo_path)
            out["aidev_total_repositories_table"] = int(len(repos))
        except Exception as exc:
            out["aidev_repositories_read_error"] = str(exc)

    return out


def _universe_stats(t_raw: AnalysisTables, t_dedup: AnalysisTables) -> dict[str, Any]:
    u_raw = t_raw.universe
    u_dedup = t_dedup.universe
    out: dict[str, Any] = {}
    if u_raw is None or u_raw.empty:
        return {"note": "universe parquet missing"}

    # PR-level counts (universe is keyed on (pr_id, sha); drop SHA dim for PR counts).
    prs_raw = u_raw.drop_duplicates(subset=["pr_id"]) if "pr_id" in u_raw.columns else u_raw
    prs_dedup = u_dedup.drop_duplicates(subset=["pr_id"]) if "pr_id" in u_dedup.columns else u_dedup

    out["universe_rows_raw"] = _safe_len(u_raw)
    out["universe_rows_dedup"] = _safe_len(u_dedup)
    out["universe_unique_prs_raw"] = _safe_len(prs_raw)
    out["universe_unique_prs_dedup"] = _safe_len(prs_dedup)

    for col, key in (("agent", "prs_per_agent"), ("language", "prs_per_language"),
                     ("pr_task_type", "prs_per_task_type"), ("state", "prs_per_state")):
        if col in prs_dedup.columns:
            out[key] = prs_dedup[col].fillna("Unknown").value_counts().to_dict()

    repo_col = "full_name" if "full_name" in prs_dedup.columns else (
        "repo_full_name" if "repo_full_name" in prs_dedup.columns else None
    )
    if repo_col:
        out["unique_repos"] = int(prs_dedup[repo_col].nunique())

    return out


def _merges_stats(t_raw: AnalysisTables, t_dedup: AnalysisTables) -> dict[str, Any]:
    im_raw = t_raw.internal_merges
    im_dedup = t_dedup.internal_merges
    out: dict[str, Any] = {
        "internal_merges_rows_raw": _safe_len(im_raw),
        "internal_merges_rows_dedup": _safe_len(im_dedup),
    }
    if im_raw is None or im_raw.empty:
        return out

    key_cols = [c for c in ("repo_full_name", "merge_sha") if c in im_raw.columns]
    if len(key_cols) == 2:
        out["unique_physical_merges"] = int(im_raw.drop_duplicates(subset=key_cols).shape[0])

    # PR fan-out: how many PRs reference each physical merge.
    if len(key_cols) == 2 and "pr_id" in im_raw.columns:
        fan = pr_fanout(im_raw)
        fan_desc = descriptive_table(fan["n_prs"])
        out["pr_fanout_desc"] = _series_to_dict(fan_desc)
        out["pr_fanout_hist"] = fan["n_prs"].value_counts().sort_index().to_dict()
        out["merges_with_multiple_prs"] = int((fan["n_prs"] > 1).sum())
        out["merges_with_multiple_prs_pct"] = _pct(
            (fan["n_prs"] > 1).sum(), fan.shape[0],
        )

    if "resolver_type" in im_dedup.columns:
        out["resolver_breakdown"] = (
            im_dedup["resolver_type"].fillna("Unknown").value_counts().to_dict()
        )

    return out


def _characterisation_section() -> dict[str, Any]:
    t_raw = load_tables(deduplicate=False)
    t_dedup = load_tables(deduplicate=True)

    chunks_raw = t_raw.classified_chunks
    chunks_dedup = t_dedup.classified_chunks
    resolved_raw = t_raw.resolved_chunks
    resolved_dedup = t_dedup.resolved_chunks

    section: dict[str, Any] = {
        "data_dir": str(DATA_DIR),
        "raw_aidev": _raw_aidev_universe_stats(),
        "universe": _universe_stats(t_raw, t_dedup),
        "internal_merges": _merges_stats(t_raw, t_dedup),
        "classified_chunks": {
            "rows_raw": _safe_len(chunks_raw),
            "rows_dedup": _safe_len(chunks_dedup),
        },
        "resolved_chunks": {
            "rows_raw": _safe_len(resolved_raw),
            "rows_dedup": _safe_len(resolved_dedup),
        },
        "extraction_errors": {
            "rows": _safe_len(t_dedup.extraction_errors),
        },
    }

    # Headline counts the paper quotes in the Dataset Overview.
    im_dedup = t_dedup.internal_merges
    conflicting_merges = 0
    if not im_dedup.empty and not chunks_dedup.empty:
        key = ["repo_full_name", "merge_sha"]
        conflicting_merges = int(
            chunks_dedup[key].drop_duplicates().shape[0]
        )
    # PR-level counts: PRs that have at least one internal merge and at least
    # one conflicting merge.  build_pr_frame joins the per-PR merge/chunk
    # aggregates onto the universe, so has_internal_merge and has_conflict are
    # already computed there.
    pr_frame = build_pr_frame(t_dedup)
    n_prs_with_internal_merge = int(pr_frame["has_internal_merge"].sum()) if not pr_frame.empty else 0
    n_prs_with_conflict = int(pr_frame["has_conflict"].sum()) if not pr_frame.empty else 0
    n_prs_total = int(pr_frame.shape[0]) if not pr_frame.empty else 1  # avoid division by zero

    section["headline"] = {
        "n_projects": section["universe"].get("unique_repos"),
        "n_prs": section["universe"].get("universe_unique_prs_dedup"),
        "n_prs_with_internal_merge": n_prs_with_internal_merge,
        "pct_prs_with_internal_merge": _pct(n_prs_with_internal_merge, n_prs_total),
        "n_prs_with_conflicting_merge": n_prs_with_conflict,
        "pct_prs_with_conflicting_merge": _pct(n_prs_with_conflict, n_prs_total),
        "n_internal_merges": _safe_len(im_dedup),
        "n_conflicting_merges": conflicting_merges,
        "n_conflict_chunks": _safe_len(chunks_dedup),
        "conflicting_merges_pct": _pct(conflicting_merges, _safe_len(im_dedup)),
    }

    # Strata on the merge frame -- useful for the paper's "per-agent /
    # per-language / per-task-type" one-liners in the Dataset Overview.
    merge_frame = build_merge_frame(t_dedup)
    for axis_col, label in (
        ("agent", "merges_per_agent"),
        ("language_top", "merges_per_language_top"),
        ("pr_task_type", "merges_per_task_type"),
    ):
        if axis_col in merge_frame.columns:
            vc = merge_frame[axis_col].fillna("Unknown").value_counts()
            section["headline"][label] = vc.to_dict()
            section["headline"][label + "_conflict_rate"] = {
                str(k): _pct(
                    int(merge_frame[
                        (merge_frame[axis_col] == k) & merge_frame["has_conflict"]
                    ].shape[0]),
                    int(vc.get(k, 0)),
                )
                for k in vc.index
            }

    return section


# --------------------------------------------------------------------------- #
# RQ1 -- Structural nature
# --------------------------------------------------------------------------- #


def _rq1_section(t: AnalysisTables) -> dict[str, Any]:
    chunks = build_chunk_frame(t)
    merges = build_merge_frame(t)
    prs = build_pr_frame(t)

    out: dict[str, Any] = {}

    if not merges.empty and "n_chunks" in merges.columns:
        # Among ALL merges (including no-conflict ones).
        out["chunks_per_merge_all_desc"] = _series_to_dict(
            descriptive_table(merges["n_chunks"])
        )
        # Among merges that produced at least one conflict chunk.
        conflicting = merges[merges["has_conflict"]]
        if not conflicting.empty:
            out["chunks_per_merge_conflicting_desc"] = _series_to_dict(
                descriptive_table(conflicting["n_chunks"])
            )

    # LOC stats per side (V1 / V2 / Base / Resolution).
    if not chunks.empty:
        for loc_col in ("v1_loc", "v2_loc", "base_loc", "resolution_loc"):
            if loc_col in chunks.columns:
                out[f"{loc_col}_desc"] = _series_to_dict(
                    descriptive_table(chunks[loc_col].dropna())
                )

        # Localization success rate.
        if "localized_ok" in chunks.columns:
            total = int(chunks.shape[0])
            ok = int(chunks["localized_ok"].sum())
            out["localized_ok"] = {
                "ok": ok,
                "total": total,
                "pct": _pct(ok, total),
            }

        # Decomposition of the Imprecise bucket into its two distinct sources:
        #   (a) localization_failures: LocalizeResRegion could not anchor the
        #       resolution region -> resolution is None -> strategy_raw = "Imprecise"
        #   (b) postponed: localization succeeded but the resolved file still
        #       contained conflict markers (<<<<<<<, =======, >>>>>>>) ->
        #       strategy_raw = "Postponed" -> folded into canonical "Imprecise"
        # This decomposition is needed because the two phenomena have different
        # methodological implications.
        if "strategy_raw" in chunks.columns and "localized_ok" in chunks.columns:
            n_loc_fail = int((~chunks["localized_ok"]).sum())
            n_postponed = int((chunks["strategy_raw"] == "Postponed").sum())
            out["imprecise_decomposition"] = {
                "localization_failures": n_loc_fail,
                "postponed": n_postponed,
                "total_imprecise": n_loc_fail + n_postponed,
                "note": (
                    "localization_failures = chunks where LocalizeResRegion returned None; "
                    "postponed = chunks where localization succeeded but resolved file "
                    "still contained conflict markers"
                ),
            }

    # PR outcome breakdown (resolved / abandoned / open-with-conflict).
    if not prs.empty and "pr_outcome" in prs.columns:
        out["pr_outcome"] = prs["pr_outcome"].value_counts().to_dict()

    # Conflict incidence per stratum.
    if not prs.empty and "has_conflict" in prs.columns:
        incidence: dict[str, dict[str, float]] = {}
        for axis_col, label in (
            ("agent", "per_agent"),
            ("language_top", "per_language_top"),
            ("pr_task_type", "per_task_type"),
        ):
            if axis_col not in prs.columns:
                continue
            grp = prs.groupby(axis_col)["has_conflict"].agg(["sum", "count"])
            incidence[label] = {
                str(k): {
                    "n_prs": int(row["count"]),
                    "n_with_conflict": int(row["sum"]),
                    "pct_with_conflict": _pct(row["sum"], row["count"]),
                }
                for k, row in grp.iterrows()
            }
        out["conflict_incidence"] = incidence

    return out


# --------------------------------------------------------------------------- #
# RQ2 -- Resolution strategies
# --------------------------------------------------------------------------- #


def _rq2_section(t: AnalysisTables) -> dict[str, Any]:
    chunks = build_chunk_frame(t)
    if chunks.empty:
        return {"note": "no classified chunks"}

    out: dict[str, Any] = {}

    # Global distribution, including and excluding Imprecise.
    incl = strategy_distribution(chunks, exclude_imprecise=False)
    excl = strategy_distribution(chunks, exclude_imprecise=True)
    out["global_incl_imprecise"] = _series_to_dict(incl.iloc[0])
    out["global_excl_imprecise"] = _series_to_dict(excl.iloc[0])
    out["imprecise_share_global"] = float(imprecise_share(chunks))

    # Per-stratum breakdown.
    per_stratum: dict[str, Any] = {}
    for axis_col, label in (
        ("agent", "per_agent"),
        ("language_top", "per_language_top"),
        ("pr_task_type", "per_task_type"),
        ("resolver_type", "per_resolver"),
    ):
        if axis_col not in chunks.columns:
            continue
        d_incl = strategy_distribution(chunks, group_col=axis_col, exclude_imprecise=False)
        d_excl = strategy_distribution(chunks, group_col=axis_col, exclude_imprecise=True)
        imp = imprecise_share(chunks, group_col=axis_col)
        per_stratum[label] = {
            "incl_imprecise": {str(k): _series_to_dict(row) for k, row in d_incl.iterrows()},
            "excl_imprecise": {str(k): _series_to_dict(row) for k, row in d_excl.iterrows()},
            "imprecise_share": imp.to_dict() if hasattr(imp, "to_dict") else {},
        }
    out["per_stratum"] = per_stratum

    # Raw strategy counts -- useful to double-check any percentage.
    out["strategy_counts_incl_imprecise"] = (
        chunks["strategy"].value_counts().reindex(STRATEGY_ORDER, fill_value=0).to_dict()
    )

    # ---------- Postponed analysis ----------
    # "Postponed" is a raw strategy label (emitted by identify_resolution when
    # the resolved file still contains conflict markers) that is folded into
    # "Imprecise" during canonicalisation.  Exposing it separately lets us
    # quantify how many merges were committed without actually resolving the
    # conflict, and compare that rate across resolver types and agents.
    #
    # The Imprecise bucket therefore decomposes as:
    #   Imprecise = localization_failures (strategy_raw == "Imprecise")
    #             + postponed             (strategy_raw == "Postponed")
    if "strategy_raw" in chunks.columns:
        n_total = int(chunks.shape[0])
        n_imprecise_canonical = int(out["strategy_counts_incl_imprecise"].get("Imprecise", 0))
        n_postponed = int((chunks["strategy_raw"] == "Postponed").sum())
        n_loc_fail  = int((chunks["strategy_raw"] == "Imprecise").sum())

        postponed_out: dict[str, Any] = {
            "n_postponed_total":          n_postponed,
            "pct_postponed_of_total":     _pct(n_postponed, n_total),
            "pct_postponed_of_imprecise": _pct(n_postponed, n_imprecise_canonical),
            "n_localization_failures":    n_loc_fail,
            "pct_loc_fail_of_total":      _pct(n_loc_fail, n_total),
            "pct_loc_fail_of_imprecise":  _pct(n_loc_fail, n_imprecise_canonical),
            "total_imprecise_check":      n_postponed + n_loc_fail,
            "note": (
                "total_imprecise_check should equal "
                "strategy_counts_incl_imprecise['Imprecise']. "
                "Any gap indicates raw strategy values not yet in _RAW_TO_CANONICAL."
            ),
        }

        def _postponed_group_stats(g: pd.DataFrame) -> pd.Series:
            n = len(g)
            n_post = int((g["strategy_raw"] == "Postponed").sum())
            n_fail = int((g["strategy_raw"] == "Imprecise").sum())
            n_imp = n_post + n_fail
            return pd.Series({
                "n_chunks":               n,
                "n_postponed":            n_post,
                "pct_postponed":          _pct(n_post, n),
                "n_localization_failure": n_fail,
                "pct_localization_failure": _pct(n_fail, n),
                "n_imprecise_total":      n_imp,
                "pct_imprecise_total":    _pct(n_imp, n),
            })

        # By resolver_type (agent / human / agent-assisted).
        if "resolver_type" in chunks.columns:
            grp = chunks.groupby("resolver_type", observed=True).apply(
                _postponed_group_stats
            )
            postponed_out["by_resolver_type"] = {
                str(idx): {
                    kk: (float(vv) if isinstance(vv, float) else int(vv))
                    for kk, vv in row.items()
                }
                for idx, row in grp.iterrows()
            }

        # By agent.
        if "agent" in chunks.columns:
            grp_agent = chunks.groupby("agent", observed=True).apply(
                _postponed_group_stats
            )
            postponed_out["by_agent"] = {
                str(idx): {
                    kk: (float(vv) if isinstance(vv, float) else int(vv))
                    for kk, vv in row.items()
                }
                for idx, row in grp_agent.iterrows()
            }

        out["postponed_analysis"] = postponed_out

    return out


# --------------------------------------------------------------------------- #
# RQ3 -- Resolver
# --------------------------------------------------------------------------- #


def _rq3_section(t: AnalysisTables) -> dict[str, Any]:
    chunks = build_chunk_frame(t)
    merges = build_merge_frame(t)

    out: dict[str, Any] = {}

    if not merges.empty and "resolver_type" in merges.columns:
        vc = merges["resolver_type"].fillna("Unknown").value_counts()
        out["resolver_counts_merge_level"] = vc.to_dict()
        out["resolver_share_merge_level"] = (vc / vc.sum()).to_dict()

    if not chunks.empty and "resolver_type" in chunks.columns:
        # Agent vs human chunk-level strategy shares, Imprecise excluded (paper convention).
        sub = chunks[chunks["resolver_type"].isin(["agent", "human"])]
        if not sub.empty:
            dist_excl = strategy_distribution(sub, group_col="resolver_type", exclude_imprecise=True)
            dist_incl = strategy_distribution(sub, group_col="resolver_type", exclude_imprecise=False)
            out["strategy_by_resolver_excl_imprecise"] = {
                str(k): _series_to_dict(row) for k, row in dist_excl.iterrows()
            }
            out["strategy_by_resolver_incl_imprecise"] = {
                str(k): _series_to_dict(row) for k, row in dist_incl.iterrows()
            }
            out["imprecise_share_by_resolver"] = imprecise_share(
                sub, group_col="resolver_type"
            ).to_dict()

    # Resolver x agent cross-tab -- who resolves the conflicts that agent-opened PRs raise?
    if not merges.empty and {"agent", "resolver_type"}.issubset(merges.columns):
        ct = pd.crosstab(
            merges["agent"].fillna("Unknown"),
            merges["resolver_type"].fillna("Unknown"),
        )
        out["resolver_by_agent_counts"] = {
            str(idx): row.to_dict() for idx, row in ct.iterrows()
        }
        ct_pct = ct.div(ct.sum(axis=1), axis=0)
        out["resolver_by_agent_shares"] = {
            str(idx): _series_to_dict(row) for idx, row in ct_pct.iterrows()
        }

    return out


# --------------------------------------------------------------------------- #
# Plain-text renderer
# --------------------------------------------------------------------------- #


def _render_txt(summary: dict[str, Any]) -> str:
    lines: list[str] = []

    def header(txt: str) -> None:
        lines.append("")
        lines.append("=" * len(txt))
        lines.append(txt)
        lines.append("=" * len(txt))

    def subhead(txt: str) -> None:
        lines.append("")
        lines.append(txt)
        lines.append("-" * len(txt))

    def kv(label: str, value: Any) -> None:
        if isinstance(value, float):
            lines.append(f"  {label}: {value:,.4f}")
        elif isinstance(value, int):
            lines.append(f"  {label}: {value:,}")
        else:
            lines.append(f"  {label}: {value}")

    def dump_dict(d: dict[str, Any], indent: int = 2) -> None:
        pad = " " * indent
        for k, v in d.items():
            if isinstance(v, dict):
                lines.append(f"{pad}{k}:")
                dump_dict(v, indent + 2)
            elif isinstance(v, float):
                lines.append(f"{pad}{k}: {v:,.4f}")
            elif isinstance(v, int):
                lines.append(f"{pad}{k}: {v:,}")
            else:
                lines.append(f"{pad}{k}: {v}")

    header("DATASET CHARACTERISATION")
    dump_dict(summary.get("characterisation", {}))

    header("RQ1 -- STRUCTURAL NATURE")
    dump_dict(summary.get("rq1", {}))

    header("RQ2 -- RESOLUTION STRATEGIES")
    dump_dict(summary.get("rq2", {}))

    header("RQ3 -- RESOLVER")
    dump_dict(summary.get("rq3", {}))

    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #


def main() -> None:
    print(f"[run_all_analyses] loading tables from {DATA_DIR}", flush=True)
    tables = load_tables(deduplicate=True)

    summary: dict[str, Any] = {}
    print("[run_all_analyses] dataset characterisation...", flush=True)
    summary["characterisation"] = _characterisation_section()
    print("[run_all_analyses] RQ1...", flush=True)
    summary["rq1"] = _rq1_section(tables)
    print("[run_all_analyses] RQ2...", flush=True)
    summary["rq2"] = _rq2_section(tables)
    print("[run_all_analyses] RQ3...", flush=True)
    summary["rq3"] = _rq3_section(tables)

    json_path = RESULTS_DIR / "results_summary.json"
    txt_path = RESULTS_DIR / "results_summary.txt"
    json_path.write_text(
        json.dumps(summary, indent=2, default=str, ensure_ascii=False),
        encoding="utf-8",
    )
    txt_path.write_text(_render_txt(summary), encoding="utf-8")

    print(f"[run_all_analyses] wrote {json_path}", flush=True)
    print(f"[run_all_analyses] wrote {txt_path}", flush=True)
    print("[run_all_analyses] done.", flush=True)


if __name__ == "__main__":
    main()
